services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php81_dev
    volumes:
      - ./:/var/www/html # Ton code PHP en local
    ports:
      - "8080:80"
    environment:
      PHP_ERROR_REPORTING: "E_ALL"
      PHP_DISPLAY_ERRORS: "1"
      PHP_MEMORY_LIMIT: "512M"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    container_name: mariadb_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pokemonzoo
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data:
